import pandas as pd

words = pd.read_csv("words.csv", dtype={"word": str})

rule all:
    input: 
        "results/sum_letter_counts/summed.txt"

rule count_letters:
    input:
    output:
        "results/count_letters/{word}.txt"
    shell:
        """
        printf "{wildcards.word}" | wc -c > {output}

        """

rule sum_letter_counts:
    input:
        expand("results/count_letters/{prefix}.txt", prefix=words['word'])
    output:
        "results/sum_letter_counts/summed.txt"
    shell:
        """
        cat {input} | awk '{{sum += $1}} END {{print "Total:", sum}}' > {output}

        """
